version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    target: dev
    
    environment:
      - HOST=0.0.0.0
      - DEBUG=1

    env_file: ./.env
    ports:
      - "8001:8000"
      - "8000:8080"

    volumes:
      - ./app:/app
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf

    command: bash /app/start.sh

    # networks:
    #   - groupeffect_net

# networks:
#   groupeffect_net:
#     external: true