services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    target: dev
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - DEBUG=1
    ports:
      - "8001:8080"
      - "8000:80"
    volumes:
      - ./app:/app
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf

    command: bash /app/start.sh

    # networks:
    #   - groupeffect_net

# networks:
#   groupeffect_net:
#     external: true